-- 创建学生表
CREATE TABLE Student(
	SNO NVARCHAR2(20),
	SNAME NVARCHAR2(20),
	SAGE NUMBER(3),
	SSEX VARCHAR2(2)
)
-- 插学生表数据
INSERT INTO Student(SNO,SNAME,SAGE,SSEX) VALUES ('1' , '张三' , 20 , '男' );
INSERT INTO Student(SNO,SNAME,SAGE,SSEX) VALUES ('2' , '李四' , 19 , '女' );
INSERT INTO Student(SNO,SNAME,SAGE,SSEX) VALUES ('3' , '王五' , 22 , '男' );
INSERT INTO Student(SNO,SNAME,SAGE,SSEX) VALUES ('4' , '赵六' , 29 , '女' );

-- 创建课程表
CREATE TABLE COURSE(
	CNO NVARCHAR2(20),
	CNAME NVARCHAR2(20),
	TNO NVARCHAR2(20)
)
-- 插课程表数据
INSERT INTO COURSE (CNO , CNAME , TNO) VALUES ('001' , '语文' , '3');
INSERT INTO COURSE (CNO , CNAME , TNO) VALUES ('002' , '数学' , '2');
INSERT INTO COURSE (CNO , CNAME , TNO) VALUES ('003' , '英语' , '1');

-- 创建成绩表
CREATE TABLE SC(
	SNO NVARCHAR2(20),
	CNO NVARCHAR2(20),
	SCORE NUMBER(3)
)
-- 插成绩表数据
INSERT INTO SC (SNO , CNO , SCORE) VALUES ('1' , '001' , 800);
INSERT INTO SC (SNO , CNO , SCORE) VALUES ('1' , '002' , 70);
INSERT INTO SC (SNO , CNO , SCORE) VALUES ('2' , '001' , 50);
INSERT INTO SC (SNO , CNO , SCORE) VALUES ('2' , '002' , 60);
INSERT INTO SC (SNO , CNO , SCORE) VALUES ('2' , '003' , 70);
INSERT INTO SC (SNO , CNO , SCORE) VALUES ('3' , '003' , 90);

-- 创建教师表
CREATE TABLE TEACHER(
	TNO NVARCHAR2(20),
	TNAME NVARCHAR2(20)
)
-- 插教师表数据
INSERT INTO TEACHER (TNO , TNAME ) VALUES ('1' , '张老师' );
INSERT INTO TEACHER (TNO , TNAME ) VALUES ('2' , '王老师' );
INSERT INTO TEACHER (TNO , TNAME ) VALUES ('3' , '李老师' );