-- 多表查询

-- 等值连接
-- 查询EMPLOYEES和DEPARTMENTS表中DEPARTMENT_ID相等的人的EMPLOYEE_ID、FIRST_NAME和DEPARTMENT_NAME
-- SELECT E.EMPLOYEE_ID "员工ID",E.FIRST_NAME "员工名字",D.DEPARTMENT_NAME "部门名字" FROM EMPLOYEES E,DEPARTMENTS D WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
-- 99连接
-- 查询EMPLOYEES和DEPARTMENTS表中DEPARTMENT_ID相等的人的EMPLOYEE_ID、FIRST_NAME和DEPARTMENT_NAME
-- SELECT E.EMPLOYEE_ID "员工ID",E.FIRST_NAME "员工名字",D.DEPARTMENT_NAME "部门名字" FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID

-- 外部链接
-- 查询EMPLOYEES和DEPARTMENTS表中DEPARTMENT_ID相等的人的EMPLOYEE_ID、FIRST_NAME和DEPARTMENT_NAME,DEPARTMENT_NAME为空也显示（有的员工无部门）
-- SELECT E.EMPLOYEE_ID "员工ID",E.LAST_NAME "员工名字",D.DEPARTMENT_NAME "部门名字" FROM EMPLOYEES E,DEPARTMENTS D WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID(+)
-- 查询EMPLOYEES和DEPARTMENTS表中DEPARTMENT_ID相等的人的EMPLOYEE_ID、FIRST_NAME和DEPARTMENT_NAME,EMPLOYEE_ID、FIRST_NAME为空也显示（有的部门无员工）
-- SELECT E.EMPLOYEE_ID "员工ID",E.LAST_NAME "员工名字",D.DEPARTMENT_NAME "部门名字" FROM EMPLOYEES E,DEPARTMENTS D WHERE E.DEPARTMENT_ID(+) = D.DEPARTMENT_ID

-- 等值+条件
-- 查询EMPLOYEES和DEPARTMENTS表中DEPARTMENT_ID相等、EMPLOYEE_ID大于200的人的EMPLOYEE_ID、FIRST_NAME和DEPARTMENT_NAME
-- SELECT E.EMPLOYEE_ID "员工ID",E.FIRST_NAME "员工名字",D.DEPARTMENT_NAME "部门名字" FROM EMPLOYEES E,DEPARTMENTS D WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND E.EMPLOYEE_ID > 200

-- 练习1   PPT5
-- 写一个查询，显示所有员工姓名，部门编号，部门名称
-- SELECT E.FIRST_NAME "员工姓名",D.DEPARTMENT_ID "部门编号",D.DEPARTMENT_NAME "部门名称" FROM EMPLOYEES E,DEPARTMENTS D WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
-- 写一个查询，显示所有工作在CHICAGO并且奖金不为空的员工姓名，工作地点，奖金
-- SELECT E.LAST_NAME "员工姓名",L.CITY "工作地点",E.SALARY "奖金" FROM EMPLOYEES E,LOCATIONS L,DEPARTMENTS D WHERE L.LOCATION_ID = D.LOCATION_ID AND D.DEPARTMENT_ID = E.DEPARTMENT_ID AND L.CITY = 'CHICAGO' AND E.SALARY <> 0
-- 写一个查询，显示所有姓名中含有A字符的员工姓名，工作地点
-- SELECT E.LAST_NAME "员工姓名",L.CITY "工作地点" FROM EMPLOYEES E,LOCATIONS L,DEPARTMENTS D WHERE L.LOCATION_ID = D.LOCATION_ID AND D.DEPARTMENT_ID = E.DEPARTMENT_ID AND E.LAST_NAME = '%a%'

-- 自连接
-- 查询员工的上级是谁
-- SELECT E.FIRST_NAME||' leader is '||M.FIRST_NAME FROM EMPLOYEES E,EMPLOYEES M WHERE E.MANAGER_ID = M.EMPLOYEE_ID

--左外连接
-- 查询EMPLOYEES和DEPARTMENTS表中DEPARTMENT_ID相等的人的EMPLOYEE_ID、FIRST_NAME和DEPARTMENT_NAME（有的员工无部门）
-- SELECT E.EMPLOYEE_ID "员工ID",E.FIRST_NAME "员工名字",D.DEPARTMENT_NAME "部门名字" FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID

-- 全连接 FULL OUTER JOIN
-- 查询EMPLOYEES和DEPARTMENTS表中DEPARTMENT_ID相等的人的EMPLOYEE_ID、FIRST_NAME和DEPARTMENT_NAME（全显示）
-- SELECT E.EMPLOYEE_ID "员工ID",E.FIRST_NAME "员工名字",D.DEPARTMENT_NAME "部门名字" FROM EMPLOYEES E FULL OUTER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID