-- 子查询

-- ANY
-- 查询部门编号不为80，切工资比80部门任意一名员工工资高的员工（就是显示高于80部门最低工资）
-- SELECT * FROM EMPLOYEES WHERE SALARY > ANY(SELECT E.SALARY FROM EMPLOYEES E WHERE E.DEPARTMENT_ID = 80) AND DEPARTMENT_ID <> 80
-- 查询部门编号不为80，切工资比80部门任意一名员工工资高的员工（就是显示高于80部门最高工资）
-- SELECT * FROM EMPLOYEES WHERE SALARY > ALL(SELECT E.SALARY FROM EMPLOYEES E WHERE E.DEPARTMENT_ID = 80) AND DEPARTMENT_ID <> 80

--多列子查询
-- 查询出2003年入职的任意一个员工的部门和职位完全相同员工姓名、部门、入职时间、员工ID，不包括2003年入职员工
-- SELECT FIRST_NAME,LAST_NAME,JOB_ID,HIRE_DATE,DEPARTMENT_ID FROM EMPLOYEES WHERE (DEPARTMENT_ID,JOB_ID)IN(SELECT DEPARTMENT_ID,JOB_ID FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE,'YYYY') = '2003')AND TO_CHAR(HIRE_DATE,'YYYY')<>2003

-- 哪些人是经理
-- SELECT FIRST_NAME||' '||LAST_NAME,JOB_ID,SALARY,DEPARTMENT_ID FROM EMPLOYEES E WHERE EXISTS(SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE MANAGER_ID = E.EMPLOYEE_ID)