--WHERE 条件查询

-- 查询EMPLOYEES表全部
--  SELECT * FROM EMPLOYEES
-- 查询EMPLOYEES中DEPARTMENT_ID=100的人，显示EMPLOYEE_ID和FIRST_NAME两列
-- SELECT EMPLOYEE_ID,FIRST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID=100
-- 查询EMPLOYEES表中FIRST_NAME = 'Steven'的全部信息
-- SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'Steven'

--比较
-- 查询EMPLOYEES表中SALARY > 10000且DEPARTMENT_ID = 80的人，显示EMPLOYEE_ID,FIRST_NAME两列
-- SELECT EMPLOYEE_ID,FIRST_NAME FROM EMPLOYEES WHERE SALARY > 10000 AND DEPARTMENT_ID = 80

--<> 不等于
-- 查询EMPLOYEES中SALARY不等于24000的人的EMPLOYEE_ID,FIRST_NAME两列
-- SELECT EMPLOYEE_ID,FIRST_NAME FROM EMPLOYEES WHERE SALARY <> 24000

-- 比较日期
-- 查询EMPLOYEES中HIRE_DATE>17-JUNE-2007的人的EMPLOYEE_ID,FIRST_NAME,HIRE_DATE三列按照HIRE_DATE排序
-- SELECT EMPLOYEE_ID,FIRST_NAME,HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE>'17-JUNE-2007' ORDER BY HIRE_DATE
-- 用函数求上面的
-- SELECT EMPLOYEE_ID,FIRST_NAME,HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE> TO_DATE('2008-01-01','yyyy-MM-dd') ORDER BY HIRE_DATE

-- 练习题1PPT3
-- 查询职位为SALESMAN的员工编号、职位、入职日期
-- SELECT EMPLOYEE_ID,EMAIL,HIRE_DATE FROM EMPLOYEES WHERE EMAIL='SALESMAN'
-- 查询1985年12月31日之前入职的员工姓名及入职时间
-- SELECT FIRST_NAME,HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE < TO_DATE('1985-12-31', 'yyyy-MM-dd') ORDER BY HIRE_DATE
-- 查询部门FIRST_NAME,HIRE_DATE编号不在10部门的员工姓名、部门编号
-- SELECT FIRST_NAME,DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID <> 10

-- BETWEEN AND 在。。。。之间
-- 查询EMPLOYEES表中SALARY在10000到20000的EMPLOYEE_ID,FIRST_NAME两列
-- SELECT EMPLOYEE_ID,FIRST_NAME FROM EMPLOYEES WHERE SALARY BETWEEN 10000 AND 20000
-- 查询EMPLOYEES中HIRE_DATE在2002年1月1号到2002年12月31号入职的人的EMPLOYEE_ID,FIRST_NAME,HIRE_DATE三列
-- SELECT EMPLOYEE_ID,FIRST_NAME,HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE BETWEEN TO_DATE('2002-01-01', 'yyyy-MM-dd') AND TO_DATE('2002-12-31', 'yyyy-MM-dd')

-- IN 满足（）里的任何一个
-- 查询EMPLOYEES表中DEPARTMENT_ID在30和90的人的MPLOYEE_ID,FIRST_NAME,DEPARTMENT_ID三列
-- SELECT EMPLOYEE_ID,FIRST_NAME,DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID IN (30，90)
-- IN的实际应用
-- SELECT EMPLOYEE_ID,FIRST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID IN(
--   SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'Executive' OR DEPARTMENT_NAME = 'IT'
-- )

-- 练习题2PPT3
-- 查询入职日期在82年至85年的员工姓名，入职日期。
-- SELECT FIRST_NAME,HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE BETWEEN TO_DATE('1982-01-01','yyyy-MM-dd') AND TO_DATE('1985-12-31','yyyy-MM-dd')
-- 查询月薪在3000到5000的员工姓名，月薪。
-- SELECT FIRST_NAME,SALARY FROM EMPLOYEES WHERE SALARY BETWEEN 3000 AND 5000 ORDER BY SALARY
-- 查询部门编号为10或者20的员工姓名，部门编号。
-- SELECT E.FIRST_NAME,D.DEPARTMENT_ID FROM EMPLOYEES E,DEPARTMENTS D WHERE D.DEPARTMENT_ID = 10 OR D.DEPARTMENT_ID = 20
-- 查询经理编号为7902,7566,7788的员工姓名，经理编号
-- SELECT FIRST_NAME,MANAGER_ID FROM EMPLOYEES WHERE MANAGER_ID IN(7902,7566,7788)

-- 模糊查询LIKE
-- 查询EMPLOYEES表中FIRST_NAME中以s结尾的人的EMPLOYEE_ID,FIRST_NAME两列
-- SELECT EMPLOYEE_ID,FIRST_NAME FROM EMPLOYEES WHERE FIRST_NAME LIKE '%s'

-- IS NULL 判断是否为空
-- 查询EMPLOYEES表中MANAGER_ID为空的人的FIRST_NAME,MANAGER_ID两列
-- SELECT FIRST_NAME,MANAGER_ID FROM EMPLOYEES WHERE MANAGER_ID IS NULL

-- 练习题3PPT3
-- 查询员工姓名以W开头的员工姓名。
-- SELECT FIRST_NAME FROM EMPLOYEES WHERE FIRST_NAME LIKE 'W%'
-- 查询员工姓名倒数第二个字符为T的员工姓名。
-- SELECT FIRST_NAME FROM EMPLOYEES WHERE FIRST_NAME LIKE '%T_'
-- 查询佣金为空的员工姓名，佣金。
-- SELECT FIRST_NAME,COMMISSION_PCT FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL

-- 排序 ORDER BY
-- SELECT EMPLOYEE_ID,FIRST_NAME,SALARY "年薪" FROM EMPLOYEES ORDER BY "年薪" DESC