--结构化查询语法  SQL(COL列，TABLE表)

--查询全部
--SELECT * FROM TABLE

--投影查询
--SELECT COL1 , COL2 FROM TABLE

--运算符
--SELECT COL1 , COL2*0.8 FROM TABLE

--别名
--SELECT COL1 , (COL2*0.8) [AS] "年薪" FROM TABLE

--NULL
--SELECT SALARY + COMM FROM EMPLOYEES   → NULL + ANY = NULL

-- ||连接运算符
-- SELECT FIRST_NAME||LAST_NEMA FROM EMPLOYEES
-- 原义字符串
-- SELECT FIRST_NAME|' '|LAST_NEMA FROM EMPLOYEES

-- DISTINCT 去掉重复内容查询
-- SELECT DISTINCT COUNTRY_ID FROM LOCATIONS