--聚合函数

-- 最大值(MAX)最小值(MIN)
-- 查询EMPLOYEES表中最大薪资和最小薪资
-- SELECT MAX(e.SALARY),MIN(e.SALARY) FROM EMPLOYEES e

--统计总数(COUNT)
-- 查询EMPLOYEES表中共多少人
-- SELECT COUNT(e.EMPLOYEE_ID) FROM EMPLOYEES e
-- 查询DEPARTMENTS表中共有多少部门
-- SELECT COUNT(d.DEPARTMENT_ID) FROM DEPARTMENTS d

-- 求和(sum)
-- 求EMPLOYEES表中工资总数
-- SELECT SUM(e.SALARY) FROM EMPLOYEES e

-- 平均值(avg)
-- 求EMPLOYEES表中薪资的平均值并保留小数点后两位
-- SELECT ROUND(AVG(e.SALARY),2) FROM EMPLOYEES e

-- 练习题1 PPT6
-- 查询部门20的员工，每个月的工资总和及平均工资
-- SELECT SUM(e.SALARY),AVG(e.SALARY) FROM EMPLOYEES e WHERE DEPARTMENT_ID = 20
-- 查询工作在CSeattle的员工人数，最高工资及最低工资
-- SELECT MAX(e.SALARY),MIN(e.SALARY),COUNT(e.DEPARTMENT_ID) FROM EMPLOYEES e,LOCATIONS l,DEPARTMENTS d WHERE d.LOCATION_ID = l.LOCATION_ID AND l.CITY = 'Seattle' AND e.DEPARTMENT_ID = d.DEPARTMENT_ID
-- 查询员工表中一共有几种岗位类型
-- SELECT COUNT( DISTINCT e.JOB_ID) FROM EMPLOYEES e 